# Generated by Django 3.2 on 2021-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False),
        ),
    ]
