# Generated by Django 3.2 on 2021-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0002_auto_20210419_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('passCode', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
