# Generated by Django 3.2 on 2021-04-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_auto_20210420_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorInfo',
            fields=[
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('phoneNo', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='buspass',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buspass',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userRegistration.userinfo'),
        ),
    ]
