# Generated by Django 3.2 on 2021-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_userinfo_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('userID', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('pic', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='picture',
        ),
    ]
