# Generated by Django 3.2 on 2021-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0008_auto_20210517_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='accBalance',
            field=models.FloatField(default=12.0),
        ),
    ]
