# Generated by Django 3.2 on 2021-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_Location', models.CharField(default='', max_length=50)),
                ('from_Location', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('busID', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
