# Generated by Django 3.2 on 2021-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_alter_travelinfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('busID', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('xCoordinate', models.CharField(default='', max_length=100)),
                ('yCoordinate', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
