# Generated by Django 3.2 on 2021-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_complaintregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregister',
            name='userID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
