# Generated by Django 3.2 on 2021-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0005_complaintregister_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintregister',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
