# Generated by Django 3.2 on 2021-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_auto_20210606_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintregister',
            name='complaintID',
        ),
        migrations.AddField(
            model_name='complaintregister',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
